# Generated by Django 2.2.5 on 2020-10-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
