# Generated by Django 2.2.5 on 2020-10-19 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20201019_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='image',
        ),
    ]
