# Generated by Django 2.2.5 on 2020-10-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_notes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures/%Y/%m/%d/'),
        ),
    ]
